version: '3'
services:
    wordpress1:
        image: wordpress
        restart: always
        ports:
            - 3081:80
        environment:
            WORDPRESS_DB_HOST: host.docker.internal:3306
            WORDPRESS_DB_USER: wordpress1
            WORDPRESS_DB_PASSWORD: wordpress1
            WORDPRESS_DB_NAME: wordpress1
        extra_hosts:
            - "host.docker.internal:host-gateway"

    wordpress2:
        image: wordpress
        restart: always
        ports:
            - 3082:80
        environment:
            WORDPRESS_DB_HOST: host.docker.internal:3306
            WORDPRESS_DB_USER: wordpress2
            WORDPRESS_DB_PASSWORD: wordpress2
            WORDPRESS_DB_NAME: wordpress2
        extra_hosts:
             - "host.docker.internal:host-gateway"

    nginx:
       image: nginx
       restart: always
       volumes:
          - ./conf.d:/etc/nginx/conf.d/
       ports:
          - "80:80"
